name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        dotnet restore day01/day01.csproj
        dotnet restore day02/day02.csproj
    - name: Build
      run: |
        dotnet build day01/day01.csproj --configuration Release --no-restore
        dotnet build day02/day02.csproj --configuration Release --no-restore
    - name: Test
      run: |
        dotnet test day01/day01.csproj --no-restore --verbosity normal
        dotnet test day02/day02.csproj --no-restore --verbosity normal
